apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-db
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-db
  template:
    metadata:
      labels:
        app: banking-db
    spec:
      containers:
      - name: db
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: banking-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: banking-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: banking-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-storage
        emptyDir: {} # Placeholder for persistent storage
